# Generated by Django 4.2.3 on 2023-10-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("liveAt", models.DateTimeField(verbose_name="Campaign Live")),
                ("endAt", models.DateTimeField(verbose_name="Campaign End")),
                (
                    "file",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to="campaign/%Y/%m/%d/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Live", "Live"),
                            ("Stop", "Stop"),
                            ("Deliver", "Deliver"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
