# Generated by Django 4.2.3 on 2023-10-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="endAt",
            field=models.DateField(verbose_name="Campaign End"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="liveAt",
            field=models.DateField(verbose_name="Campaign Live"),
        ),
    ]
