# Generated by Django 4.2.3 on 2023-10-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_alter_campaign_endat_alter_campaign_liveat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="code",
            field=models.PositiveIntegerField(verbose_name="Campaign Code"),
        ),
    ]
