# Generated by Django 4.2.3 on 2023-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_alter_campaign_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="code",
            field=models.CharField(max_length=20, verbose_name="Campaign Code"),
        ),
    ]
